services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql-test-wporg-tsa-index
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - "6330:3306"
    command: --default-authentication-plugin=mysql_native_password

